### ISSUE TITLE
Feature agregar nueva sección de tecnologías

### ISSUE THREAD

**Issue by PedroSubia** [maxipereyra/portfolio-template#1]
# Nueva Sección de Tecnología :rocket:
Hola Maximo, según lo acordado en la reunión del Sabado 2 de Julio; te comunico que procederé a agregar la sección de tecnologías en tu portfolio.  
![image](https://user-images.githubusercontent.com/45021439/177226308-0be0abdf-8916-4417-8445-f4a0e33e76b6.png)
Saludos. :thumbsup:

**Comment by maxipereyra** [comment]
Hola Pedro muchas gracias por el aporte. 👌 :ok_hand:
